import Head from 'next/head'
import Navbar from '../components/Navbar/index'
import Section from '../components/SectionHome'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className=''>
       <div class="h-cover flex flex-col items-center justify-center bg-[url('/copy.jpg')]">
             <div>
                 <Navbar/>
                 <Section/>
             </div>
         </div>
         <h1 className='text-3xl text-center'>hahaha</h1>
       </div>
    </div>
  )
}
